- applications_guide_en/_layouts/default.html
- applications_guide_en/_layouts/development.html
- applications_guide_en/_layouts/landing.html
- applications_guide_en/_layouts/task.html
- applications_guide_en/_layouts/wip.html
default.html
development.html
landing.html
**none.html - no action required**
task.html
wip.html
> Translated layout (html) pages to EN

- werf.io/guides/nodejs/100_basic/40_must_haves.md
Updated 40_must_haves.md based on new edits in the RU version of the file.
- no code changes
> [DOCS] Updated 40_must_haves.md based on new edits in the RU version

- .github/workflows/validate.yml
- common/_include_templates/_breadcrumbs.html
- common/_include_templates/_sidebar.html
- common/_plugins/snippetcut.rb
- common/assets/css/guides.css
- common/webpack.config.js
- ru.werf.io/guides/_layouts/default.html
- ru.werf.io/guides/_layouts/development.html
- ru.werf.io/guides/_layouts/task.html
- ru.werf.io/guides/_layouts/wip.html
- ru.werf.io/guides/django/100_basic/20_cluster.md
- ru.werf.io/guides/django/100_basic/30_deploy.md
- ru.werf.io/guides/golang/100_basic/20_cluster.md
- ru.werf.io/guides/golang/100_basic/30_deploy.md
- ru.werf.io/guides/java_springboot/100_basic/20_cluster.md
- ru.werf.io/guides/java_springboot/100_basic/30_deploy.md
- ru.werf.io/guides/nodejs/100_basic/20_cluster.md
- ru.werf.io/guides/nodejs/100_basic/30_deploy.md
- ru.werf.io/guides/rails/100_basic/20_cluster.md
- ru.werf.io/guides/rails/100_basic/30_deploy.md
- werf.io/guides/_layouts/default.html
- werf.io/guides/_layouts/development.html
- werf.io/guides/_layouts/task.html
- werf.io/guides/_layouts/wip.html
- werf.io/guides/java_springboot/100_basic/20_cluster.md
- werf.io/guides/java_springboot/100_basic/30_deploy.md
- werf.io/guides/nodejs/100_basic/20_cluster.md
- werf.io/guides/nodejs/100_basic/30_deploy.md
Use topnav, footer and some styles from the main site
> [web] Use main site partials

- werf.io/guides/java_springboot/100_basic/10_build.md
- werf.io/guides/java_springboot/100_basic/30_deploy.md
- werf.io/guides/java_springboot/100_basic/40_must_haves.md
> [DOCS] syncing three EN java springboot articles with RU version

- common/assets/js/customscripts.js
- common/assets/js/details.js
> [web] Update layouts

- ru.werf.io/guides/nodejs/100_basic/10_build.md
- ru.werf.io/guides/nodejs/100_basic/20_cluster.md
- ru.werf.io/guides/nodejs/100_basic/20_cluster_minikube.md
- ru.werf.io/guides/nodejs/100_basic/30_deploy.md
Fixed only a RU nodejs guide with minikube setup, but these changes need to be applied to all the other related guides/places.
> Fix guides

- examples/rails/010_build/Dockerfile
- examples/rails/011_build_werf/Dockerfile
- examples/rails/015_deploy_app/Dockerfile
Removed excess layers rebuilds which slow down changes delivery.
> [basic][rails] Optimize dockerfile

- pages_ru/django/100_basic/30_deploy_registrysecret_remote.md
- pages_ru/golang/100_basic/30_deploy_registrysecret_remote.md
- pages_ru/java_springboot/200_real_apps/30_assets.md
- pages_ru/nodejs/100_basic/30_deploy_registrysecret_remote.md
- pages_ru/nodejs/200_real_apps/30_assets.md
- pages_ru/nodejs/200_real_apps/50_files.md
- pages_ru/nodejs/200_real_apps/60_email.md
- pages_ru/nodejs/200_real_apps/80_database.md
fix https://github.com/werf/werf-guides/issues/91
> Use .Values.werf.image instead of werf_image

- .werf/nginx-dev.conf
- docker-compose.yml
To run guides locally:
- Add ru.localhost record in your /etc/hosts
- Run `werf compose up --follow --docker-compose-command-options='-d'`
> [ci] Update instructions for local site development

- Gemfile
- Gemfile.lock
- _config.yml
```
{% uml %}
node "basicapp" {
[Rails backend]
}
node "node-assets" {
[Nginx] -- [Assets]
}
{% enduml %}
```
> [jekyll] Plantuml integration

- pages_ru/rails/100_basic/10_build.md
- pages_ru/rails/100_basic/20_cluster.md
- pages_ru/rails/100_basic/20_cluster_minikube_linux.md
- pages_ru/rails/100_basic/20_cluster_minikube_macos.md
- pages_ru/rails/100_basic/20_cluster_minikube_windows.md
- pages_ru/rails/100_basic/30_deploy.md
- pages_ru/rails/100_basic/38_kubernetes_basics.md
Kubernetes basics & shell comments are polished now.
> [basic][rails] Final text corrections

- pages_ru/rails/100_basic/35_deploy_changes.md
Use `werf converge --repo <имя пользователя Docker Hub>/werf-guided-rails`
> [100_basic] Fix werf converge command

- pages_ru/rails/200_real_apps/25_logging.md
- pages_ru/rails/200_real_apps/60_cron.md
Use `werf converge --repo <имя пользователя Docker Hub>/werf-guided-rails`.
> [200_real_apps] Fix werf converge cmd

- pages_ru/rails/100_basic/20_cluster_minikube_check.md
- pages_ru/rails/100_basic/20_cluster_minikube_linux.md
- pages_ru/rails/100_basic/20_cluster_minikube_macos.md
- pages_ru/rails/100_basic/20_cluster_minikube_windows.md
> [rails][basic] Preparing the environment: check

- pages_ru/rails/100_basic/20_cluster.md
> [rails][basic] Preparing the environment: add docker-registry secret note

- _includes/ru/100_basic/20_cluster_docker_ready.md.liquid
- _includes/ru/100_basic/20_cluster_system_restarted_minikube.md.liquid
- _includes/ru/chapter_prepare_repo_commands.md.liquid
- pages_ru/rails/100_basic/20_cluster.md
- Open the first tab by default
- Change the order of the tabs: Linux, macOS, Windows
> [100_basic] Update tabs

- _includes/en/200_real_apps.md.liquid
- _includes/en/200_real_apps/010_basic_app.md.liquid
- _includes/en/200_real_apps/010_basic_app/rails/how_basic_app_was_made.md.liquid
- examples/rails/010_basic_app/Dockerfile
- pages_en/rails/200_real_apps/020_logging.md
> [docs] Translate 200_real_apps

- _includes/en/chapter_initial_prepare_repo.md.liquid
- _includes/ru/chapter_initial_prepare_repo.md.liquid
Uncollapse "Preparing the repository" block
> site: Uncollapse "Preparing the repository" block

- pages_en/rails/100_basic/35_deploy_changes.md
English version has been brought in line with Russian on the "Applying changes" page.
> Syncing English version of Basic/Applying changes

- _includes/en/100_basic/40_must_haves.md.liquid
"werf vs Helm/Docker" articles are published, so we can mention them.
> basic(en): adding blog links to the Must have

- _includes/_common/snippetcut_example
- _includes/ru/200_real_apps/050_s3/nodejs/015_add_new_routes.md.liquid
> [feat] pass multiple snippets to snippetcut_example

- examples/nodejs/040_db/.helm/templates/job-db-setup-and-migrate.yaml
- examples/nodejs/050_s3/.helm/templates/job-db-setup-and-migrate.yaml
- examples/nodejs/080_configuration/.helm/templates/job-db-setup-and-migrate.yaml
Adde the creation of the database before migration.
> Nodejs guide: fix failing DB creation job

- _includes/en/installation/installer_windows.md
- assets/js/installation.js
- pages_en/installation.md
- pages_ru/installation.md
- rerange installation method tabs
- hide installer installation method for windows
- actualize installation.js
> docs(installation): small improvements

- _data/en/guides/ask_and_star_buttons.yaml
Change button text "Star it if you like it!" to "Leave a star if you like it!".
> Change button text

- _config_en.yml
- _config_ru.yml
- _includes/_common/toc.html
- _layouts/guides-page-base.html
Added TOC navigation in guides
> Add toc nav

- assets/css/docs-guides.scss
> refactor: fix style to soon badge

- _includes/en/guides/chapter_initial_prepare_cluster.md.liquid
Remove spoiler for "preparing the environment" blocks on en version
> fix: preparing the environment block

- _includes/en/installation/setup_buildah.md
- _includes/ru/installation/setup_buildah.md
Signed-off-by: Ilya Lesikov <ilya@lesikov.com>
> docs(installation): require kernel.unprivileged_userns_clone for Buildah

- .github/workflows/deploy.yml
> ci: update slack notification job

- examples/rails/010_basic_app/Gemfile
- examples/rails/019_fixup_consistency/Gemfile
- examples/rails/020_logging/Gemfile
- examples/rails/030_assets/Gemfile
- examples/rails/040_db/Gemfile
- examples/rails/050_s3/Gemfile
- examples/rails/080_configuration/Gemfile
- examples/rails/800_cron/Gemfile
Signed-off-by: Ilya Lesikov <ilya@lesikov.com>
> fix(guides): pin to minor ruby version in Gemfile

- backend/handlers.go
Disables directory listing if the is no `index.html` file
> site: disable directory listing

- _data/_common/channels_info.yml
- pages_en/about/release_channels.html
> docs(release_channels): rephrase / unify

- pages_en/about/changelog.html
- pages_ru/about/changelog.html
Remove unnecessary js loading.
> site: fix the changelog page

- install.sh
Signed-off-by: Ilya Lesikov <ilya@lesikov.com>
> fix(install.sh): parse non-standard semvers of git version

- install.sh
Removed quotes in awk script to parse of git version.
Signed-off-by: Timofey Kirillov <timofey.kirillov@flant.com>
> fix(install.sh): unexpected character '\'

- _includes/en/installation/setup_buildah.md
- _includes/ru/installation/setup_buildah.md
Signed-off-by: Timofey Kirillov <timofey.kirillov@flant.com>
> docs(installation): simplify installation instructions for buildah mode

- _includes/_common/head.html.liquid
- _layouts/default-guides.html
- _layouts/default.html
> fix: outdated guide page layout head

- _includes/_common/head.html.liquid
- _includes/_layouts/guides/page_to_page_guide.liquid
- pages_ru/guides/rails/200_real_apps/60_cron.md
> site: fix incomplete guide page title

- _includes/_common/head.html.liquid
- pages_ru/guides/index.md
> site: fix page title validation

- .helm/templates/_rewrites.tpl
The second part of the rewrites for the new documentation structure.
> chore: add rewrites for the new guides structure

- assets/css/index.css
- pages_en/index.md
- pages_ru/index.md
> site(index): fix configuration typos

- pages_en/guides/index.md
- pages_ru/guides/index.md
Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>
> site(guides_landing): fix footer

- werf.yaml
Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>
> chore(werf.yaml): add tag to base image

- _includes/ru/guides/400_ci_cd_workflow/030_gitlab_ci_cd/010_workflows.md.liquid
Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>
> chore: fix broken links

- pages_en/index.md
Signed-off-by: Aleksei Igrychev <aleksei.igrychev@palark.com>
> site(index): update banner tags

- pages_en/index.md
- pages_ru/index.md
Signed-off-by: Zhbert <konstantin.nezhbert@flant.com>
> Fix the number of recent publications on the main page

- .helm/templates/_rewrites.tpl
Add redirect for the /how_it_works.html page.
> chore: add redirect for the how_it_works page

- assets/css/index.css
- pages_en/index.md
- pages_ru/index.md
- update site title
- update feature card header and order
> site(index): small improvements

- _data/en/publications.yml
- _includes/en/guides/100_basic/40_must_haves.md.liquid
- _includes/en/guides/300_deployment_practices/010_life_cycle.md.liquid
Replaced outdated links to blog.flant.com on the right ones.
> Fix blog links

- _config_en.yml
- _config_ru.yml
- fix "undefined method `end_with?' for {}:Hash (NoMethodError)"
- sort items in exclude
> fix: exclude bin directory

- bin/configurator/static/_includes/ru/configurator/tab/ci/other-ci-cd-system/simple/docker-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/ru/configurator/tab/ci/other-ci-cd-system/simple/host-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/ru/configurator/tab/ci/other-ci-cd-system/simple/host-runner/linux/docker.md.liquid
- bin/configurator/static/_includes/ru/configurator/tab/ci/other-ci-cd-system/simple/kubernetes-runner/linux/buildah.md.liquid
> fix: nested curlies not allowed, use capture

- bin/configurator/static/_includes/en/configurator/tab/ci/github-actions/simple/host-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/gitlab-ci-cd/simple/docker-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/gitlab-ci-cd/simple/host-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/gitlab-ci-cd/simple/host-runner/linux/docker.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/gitlab-ci-cd/simple/kubernetes-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/gitlab-ci-cd/singlerepo/docker-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/gitlab-ci-cd/singlerepo/host-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/gitlab-ci-cd/singlerepo/host-runner/linux/docker.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/gitlab-ci-cd/singlerepo/kubernetes-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/other-ci-cd-system/simple/docker-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/other-ci-cd-system/simple/host-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/other-ci-cd-system/simple/host-runner/linux/docker.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/other-ci-cd-system/simple/kubernetes-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/dev/linux/buildah.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/dev/linux/docker.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/dev/macos/docker.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/dev/windows/docker.md.liquid
- werf.yaml
Add the **_docker.md.liquid_** and **_buildah.md.liquid_** files for various usage scenarios.
Refer to #536 for details.
> EN - Configurator generator

- bin/configurator/static/_includes/en/configurator/tab/ci/other-ci-cd-system/simple/docker-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/other-ci-cd-system/simple/host-runner/linux/buildah.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/other-ci-cd-system/simple/host-runner/linux/docker.md.liquid
- bin/configurator/static/_includes/en/configurator/tab/ci/other-ci-cd-system/simple/kubernetes-runner/linux/buildah.md.liquid
- fix markup for en site, see #558 
Problem:
> fix: nested curlies not allowed, use capture (en)

- Gemfile.lock
- _includes/_common/head-common.html
- assets/js/configurator/options.js
- assets/js/configurator/tabs.js
- bin/configurator/templates/includes/tabs.html
- bin/configurator/templates/pages/configurator.html
- Use delegated events for tab button clicks
- Split configurator.js
- Remove script from tabs.html
> fix: toggling tabs after choosing new tab

- werf.yaml
> fix: include site.webmanifest into build

- .helm/templates/_rewrites.tpl
> fix: remove run in container rewrite

- assets/js/configurator/tabs.js
- assets/js/details.js
- two handlers cancel each other
> fix: remove excess click handler

- .helm/templates/_rewrites.tpl
> Revert "chore(rewrites): moved cheat-sheet"

- .helm/templates/_rewrites.tpl
> Revert "Revert "chore(rewrites): moved cheat-sheet""

- _data/_common/install_sitemap.yml
- sitemap-site.xml
> Revert "Add configurator pages to sitemaps"

- examples/django/040_db/.helm/templates/database.yaml
- examples/django/040_db/Dockerfile
- examples/django/050_s3/.helm/templates/database.yaml
- examples/django/050_s3/Dockerfile
- examples/django/080_configuration/Dockerfile
Dockerfiles and MySQL versions have been fixed in accordance with this [issue](https://github.com/werf/website/issues/672).
> Fix Django apps

- _includes/_common/head-common.html
- assets/css/docs.css
- assets/js/sidebar-fix.js
> Revert "Fixed position sidebar, remove script for sidebar"

- .github/workflows/cleanup.yml
- .github/workflows/content_validation.yml
- .github/workflows/deploy.yml
Use enterprise runners and secrets for K8s context.
> ci: use enterprise runners

- _includes/en/guides/200_real_apps/050_s3.md.liquid
- _includes/ru/guides/200_real_apps/050_s3.md.liquid
- examples/golang/050_s3/.helm/templates/job-setup-minio.yaml
- examples/laravel/050_s3/.helm/templates/job-setup-minio.yaml
- examples/nodejs/050_s3/.helm/templates/job-setup-minio.yaml
- examples/rails/050_s3/.helm/templates/job-setup-minio.yaml
The minio availability check command in jobs has been changed.
> Fix command for minio checking in guides

- robots.txt
> Disallow /documentation/ path

- .github/workflows/deploy.yml
Notify team if deploy docs fails in main
Notify branch owner if deploy docs fails in branch
Success notify only in main
> chore(ci): update notifications

- .werf/artifacts/generate_artifacts.sh
- .werf/artifacts/get_git_history.sh
> feat: fix artifact generation scripts
