werf/website

- ru.werf.io/guides/java_springboot/100_basic/10_build.md
- werf.io/guides/java_springboot/100_basic/10_build.md
Change return type from `List<Labels>` to `String` in a springboot guide.
> fix(springboot): change return type in example changes

- pages_ru/rails/100_basic/35_deploy_changes.md
- werf-guide-app instead of example.com;
- remove git-add cmd;
- fix example link;
- some grammar fixes.
> [35_deploy_changes] Final refinements

- .github/workflows/cleanup.yml
```
Error: unable to remove repo image meta-fb496116_7b3e318b1f7027af17dacc690389a330fbd99dac_813a1fb8b8a06897d727c82b736a2c9dc5e708dd6c49504adf6fe24a-1628744443760: gitHub packages forbidden: GET https://api.github.com/orgs/werf/packages/container/werfio-guides/versions?page=REDACTED&per_page=REDACTED: unexpected status code 403 Forbidden (body: {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reference/packages#get-all-package-versions-for-a-package-owned-by-an-organization"})
You should specify a token with delete:packages and read:packages scopes to remove package versions.
Check --repo-github-token option.
Be aware that the token provided to GitHub Actions workflow is not enough to remove package versions.
Read more details here …
```
> fix(ci): cleanup container registry workflow failed

- .helm/templates/20-ingress-tuf-router.yaml
- .helm/templates/20-ingress.yaml
Update Ingress resources API version to get rid of using deprecated CRD APIs on the site.
> site: update Ingress versions

- .github/workflows/content_validation.yml
- werf.yaml
Pin the [jekyll/builder](https://hub.docker.com/r/jekyll/builder) image to the version 4.2.0. The reason is that the next tag — 4.2.2 uses ruby 3 (3.1.1) instead of ruby 2 (2.7.1) in 4.2.0. Some gems are not working with ruby 3.
> site: pin jekyll image version

- install.sh
`$USER` might not be set.
Signed-off-by: Ilya Lesikov <ilya@lesikov.com>
> fix(install.sh): user `id -un` instead of `$USER`

- _plugins/filesused.rb
- _plugins/offtopic.rb
- _plugins/snippetcut.rb
- Use context.registers to prevent parsing config file.
- Jekyll.configuration() is not correct when multiple files are used.
- Source: https://github.com/jekyll/jekyll/issues/1578#issuecomment-25109633
- TODO: update plantuml plugin after merging https://github.com/flant/jekyll_remote_plantuml_plugin/pull/8
> fix: Jekyll.configuration() is an expensive call

- robots.txt
Update robots.txt to disallow indexing werf 1.1 by search engines.
> chore: disallow indexing werf 1.1 by search engines

- .github/workflows/content_validation.yml
- Taskfile.yaml
- scripts/docs/check_broken_links.sh
Added local link checking:
- `task site:check-broken-links` – checks both versions — en and ru;
- `task site:check-broken-links:ru` – checks only ru docs;
- `task site:check-broken-links:en` – checks only en docs.
Launches a container from `werf.yaml`, and it checks the generated site.
> Add local htmlproofer

- Taskfile.yaml
- scripts/docs/spelling/internal/container_spell_check.sh
- scripts/docs/spelling/spell_check.sh
Added a parameter through which you can pass the path to the file to check it.
For example: `task site:run-spell-check:ru -- ./guides.html`.
> Add a target file selection for spell checking

- _data/_common/install_sitemap.yml
- sitemap-site.xml
Added link generation of the configurator pages in sitemaps.
The links are located in the file `_data/_common/install_sitemap.yml`:
```yaml
links:
- "usage=localDev&os=linux&buildBackend=buildah"
- "usage=localDev&os=macos&buildBackend=docker"
- "usage=localDev&os=windows&buildBackend=docker"
...
```
The result in the sitemap:
```xml
<url>
<loc>https://werf.io/documentation/v1.2/index.html?usage=localDev&os=linux&buildBackend=buildah</loc>
<xhtml:link rel="alternate" hreflang="ru" href="https://ru.werf.io/documentation/v1.2/index.html?usage=localDev&os=linux&buildBackend=buildah" />
<xhtml:link rel="alternate" hreflang="en" href="https://werf.io/documentation/v1.2/index.html?usage=localDev&os=linux&buildBackend=buildah" />
<lastmod>2023-07-11</lastmod>
<changefreq>daily</changefreq> …
```
> Add configurator pages to sitemaps

- scripts/docs/spelling/internal/container_spell_check.sh
An indication of the language of the file being checked has been added. This is necessary in order to better understand in which content the error was found, in Russian or English.
Previously, the result looked like this:
```
Checking ./configurator/tabs/usage-ci_ci-gitlabCiCd_runnerType-hostRunner_os-linux_buildBackend-buildah_projectType-bestPractice_sharedCICD-no_repoType-monorepo.html...
qemu
yaml
yaml
json
json
js
gitlab
ci
yaml
Checking ./configurator/tabs/usage-ci_ci-otherCiCdSystem_runnerType-hostRunner_os-linux_buildBackend-buildah_projectType-simplified_sharedCICD-no_repoType-application.html...
qemu
yaml
yaml
json
json
js
ci
cd
yaml
yaml
```
Now the result looks like this:
```
EN: checking ./configurator/tabs/usage-ci_ci-gitlabCiCd_runnerType-hostRunner_os-linux_buildBackend-bui …
```
> Add language indication to spell checker

- scripts/docs/spelling/internal/container_spell_check.sh
- scripts/docs/spelling/internal/filesignore
Added checking for exceptions that do not fall into the spell check.
The list of file paths to exclude is in the `scripts/docs/spelling/internal/filesignore` file. Paths are checked by a match mask. There is a separate mask on each line of the file.
For example:
* By the `guides` mask, all pages in the `/guides` section will be excluded from the check.
* By the `guides/django` mask, all pages in the `/guides/django` section will be excluded from the check.
* By mask `guides/nodejs/400_ci_cd_workflow/040_github_actions.html`a specific file will be excluded.
Currently, files from the `assets/demo` directory are excluded from the check.
> Add file and path exclusion to the spelcheck

- _data/_common/install_sitemap.yml
- sitemap-site.xml
Added link generation of the configurator pages in sitemaps.
The links are located in the file `_data/_common/install_sitemap.yml`:
```yaml
links:
- "usage=localDev&amp;os=linux&amp;amp;buildBackend=buildah"
- "usage=localDev&amp;os=macos&amp;buildBackend=docker"
- "usage=localDev&amp;os=windows&amp;buildBackend=docker"
...
```
**Pay attention!** Symbols `&` must be replaced with `&amp;`!
The result in the sitemap:
```xml
<url>
<loc>https://werf.io/documentation/v1.2/index.html?usage=localDev&os=linux&buildBackend=buildah</loc>
<xhtml:link rel="alternate" hreflang="ru" href="https://ru.werf.io/documentation/v1.2/index.html?usage=localDev&os=linux&buildBackend=buildah" />
<xhtml:link rel="alternate" hreflang="en" href="https://werf.io/documentation/v1.2/index.html?usage=localDev&os=linux&bu …
```
> Add configurator pages to sitemap

- sitemap-site.xml
The configurator tabs (`configurator/tabs/*`) have been removed from the sitemap.
> Delete the configurator tabs from the sitemap

- _includes/_common/footer.html
- _includes/_common/guides-landing-tile.html
- _includes/_common/topnav.html
- _includes/en/guides/200_real_apps/030_assets.md.liquid
- _includes/ru/guides/200_real_apps/030_assets.md.liquid
- _layouts/guides-page-base.html
- pages_en/index.md
- pages_ru/index.md
- scripts/docs/spelling/internal/container_spell_check.sh
* Added functionality for removing parts of the page from the final HTML. The necessary parts are highlighted with comments. For example:
```html
<div class="footer__block-cncf">
<a href="https://www.cncf.io/projects/werf/" target="_blank">
{%- if page.lang == "ru" %}
<div class="footer__block-cncf-text">werf — проект категории sandbox в&nbsp;Cloud Native Computing Foundation</div>
{%- else %}
<div class="footer__block-cncf-text">werf is a Cloud Native Computing Foundation sandbox project</div>
{%- endif %}
</a>
</div>
```
* Some parts of the pages with spelling errors have already been highlighted with comments.
> [spell-check] Add functionality to remove parts of a page from HTML

- .github/workflows/content_validation.yml
- scripts/docs/spelling/dictionaries/dev_OPS.dic
- scripts/docs/spelling/internal/container_spell_check.sh
- scripts/docs/spelling/wordlist
1. The spell check is divided into two separate tests: Ru and En.
2. Added exit codes for each test.
3. Empty messages about files in which nothing was found were removed from the exhaust.
4. The labels about ignoring files are left to be aware of how the ignoring mechanism works.
> [spell-check] Refactor GitHub actions and exit codes

- _data/en/publications.yml
- scripts/docs/spelling/dictionaries/dev_OPS.dic
- scripts/docs/spelling/wordlist
English-language publications got a few fixes:
- Renamed the source for all existing [werf blog](https://blog.werf.io/) entities.
- Removed external links from publications' descriptions.
- Fixed date for the latest article; fixed service names for a few old articles.
> Fix publications links & button labels

- .github/workflows/deploy.yml
Trigger Deploy on the `workflow_dispatch` event. 
Deploy will be triggered when a new [werf](https://github.com/werf/werf/) release is out.
> ci: Trigger Deploy on workflow_dispatch events

- install.sh
add function to install system dependencies for werf
add function for setup buildah
add function dynamically assigning ranges to /etc/subuid /etc/subgid
and more...
> feat(install.sh): add buildah

- _data/en/guides/ask_and_star_buttons.yaml
- _includes/_layouts/guides/ask_and_star_buttons.html
This PR fixes two current issues with the red button ("Prepare/fix the environment") at the Kubernetes guides' sidebar:
1. It was static and always led to the Ruby/Rails article.
2. It was external and always opened in a new tab/window.
>  fix(guides): fix the Prepare environment link
